# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: azure-first project

stages:

# Stage 1: Build..
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: Build
      displayName: 'Build Job'
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: '/myagent/_work/4/s/my-app/pom.xml'
          goals: 'clean install'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
        displayName: 'Maven Build'

# Stage 2: Test
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build  # Run tests only if the build succeeds
  jobs:
    - job: UnitTests
      displayName: 'Run Unit Tests -get approval'
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: '/myagent/_work/4/s/my-app/pom.xml'
          goals: 'test'  # Only run tests in this stage
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
        displayName: 'Maven Unit Tests'

# Stage 3: Deploy

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build  # Run deploy only if the build succeeds
  jobs:
  - deployment: 
    environment: 'deploy'
    strategy:
     runOnce:
       deploy:
           steps:
            - task: Maven@4
              inputs:
                mavenPomFile: '/myagent/_work/4/s/my-app/pom.xml'
                goals: 'deploy'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                javaHomeOption: 'JDKVersion'
                mavenVersionOption: 'Default'
                mavenAuthenticateFeed: false
                effectivePomSkip: false
                sonarQubeRunAnalysis: false
